### ISSUE TITLE
Add infos about dependencies

### ISSUE THREAD

**Issue by kraf** [uncomplicate/clojurecuda#1]
So first of all I'm really excited about the stuff you're doing, thanks for sharing all this!

I was following along your tutorial at http://dragan.rocks/articles/18/Interactive-GPU-Programming-1-Hello-CUDA and had a few issues with dependencies. I thought putting them in the README could make things easier for others:

- Java 8 (Java 7 not working due to fluokitten)
- GCC 5 (Standard libraries coming with 4.9 were too old)
- CUDA Toolkit 9 (because of JCuda)

I used version 3.0 from clojars.

**Comment by blueberry** [comment]
Thank you for reporting this. The trouble with the specific versions in docs is that they change from time to time, an it is easy to forget to update the guide. Now I see that the guide mentions CUDA 8 (which was current when I wrote that).

In my opinion, it is best to write the guide to clearly state how to find which version is current and where to look for the information. Specific versions may be OK too if carefully worded.

 Would you consider checking out the Getting Starded page, and improving it a bit by adding the information that you think is relevant, and removing what's not needed? It's in the gh-pages branch, and a PR would be appreciated.

**Comment by kraf** [comment]
I'll check it out and update it

**Comment by kraf** [comment]
I'm still on this, sorry for taking so long. I'm not allowed to install CUDA 9 where I was trying out the tutorial and had issues with setting up a cloud instance with an Nvidia card, among others building GCC5 there, which takes forever (CentOS 7 only has GCC 4.8.5, which is rather common). I tried Debian 9 first, but installing the toolkit & drivers there was just too much of a hassle. Once I'll get everything to run, I'll update the Getting Started page.

**Comment by blueberry** [comment]
Thanks for the update, and appologies for taking so long to merge the PR.
