### ISSUE TITLE
cuRAND?

### ISSUE THREAD

**Issue by sdedovic** [uncomplicate/clojurecuda#13]
Are you planning to add any cuRAND APIs to this library? I've started a simple wrapper, in a similar style to your code, for some of my own needs, [here](https://github.com/sdedovic/artlib-cuda/blob/master/src/clj/artlib/cuda/curand.clj). I'm more than happy to contribute.

**Comment by blueberry** [comment]
Hi Stevan, Thanks! Have you seen https://neanderthal.uncomplicate.org/codox/uncomplicate.neanderthal.random.html?
Does it cover your needs in artlib, or you specifically need exactly cuRAND. I'm trying to keep the parity between CUDA and OpenCL backends in Neanderthal.

**Comment by sdedovic** [comment]
Thanks for the response.

> Have you seen https://neanderthal.uncomplicate.org/codox/uncomplicate.neanderthal.random.html? Does it cover your needs

Yes, I've dug through that quite a lot. It does cover most of my needs but I would like to stick with just the CUDA libraries as much as possible. Initially I was only using JCurand and that was sufficient. Part of this is also a learning experience for me.

<br>
<br>

> I'm trying to keep the parity between CUDA and OpenCL backends in Neanderthal.

I understand. I really just want an idiomatic Clojure wrapper over cuRAND that's as 1:1 as possible. If that doesn't fit here, that's fine, I may expand my wrapper and publish it separately.

**Comment by blueberry** [comment]
It would be interesting if you can compare the speed of philox generator in Neanderthal in cuRAND, since you've already set them up both. I'm curious.

**Comment by sdedovic** [comment]
Haven't tested performance yet but got a preliminary wrapper out: https://github.com/sdedovic/curand-clj. Will update once I get around to benchmarking.
