### ISSUE TITLE
Compatibility with CUDA Toolkit 9.1, 9.2?

### ISSUE THREAD

**Issue by Biserkov** [uncomplicate/clojurecuda#3]
At least on Windows, jCUDA 0.9.0d (latest version as of this writing) has a exact dependency on the CUDA Toolkit v.9.0 and ClojureCUDA is therefore incompatible with Toolkit version 9.1 and 9.2. 

More specifically, when running the steps from the tutorial at [dragan.rocks](https://dragan.rocks/articles/18/Interactive-GPU-Programming-1-Hello-CUDA) on Windows 10, when executing the ```(program kernel-source)``` form, the following error occurs:

```%APPDATA%\Local\Temp\JNvrtc-0.9.0-windows-x86_64.dll: Can't find dependent libraries```

Running ```dumpbin /dependents JNvrtc-0.9.0-windows-x86_64.dll``` reveals a depency on nvrtc64_90.dll which is located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\

As this seems to be an upstream (downstream?) issue, is there anything you can do? 

At the very least, can you add a note about this on Windows? 

The [blog post](https://dragan.rocks/articles/18/Neanderthal-018-CUDA9-Java9-Clojure19-update) says "ClojureCUDA now supports the latest CUDA 9.1."

**Comment by blueberry** [comment]
There is: simply add explicit dependency to jcuda 0.9.1 or 0.9.2 to your project.

As of the next version, ClojureCUDA will require CUDA 9.2 by default, but you could explicitly specify 0.9.0 or 0.9.1 (or even 0.8.0, but then I am not sure whether all functions will work properly).

**Comment by Biserkov** [comment]
Thanks a ton! 

I think it would be very helpful to add this "trick" to the tutorial.

On jcuda.org there is no mention of 0.9.1 or 0.9.2 in either news or downloads, so I assumed they were not released yet.
