### ISSUE TITLE
Stackoverflow/infinite recursion in info?

### ISSUE THREAD

**Issue by Biserkov** [uncomplicate/clojurecuda#5]
This works on 0.4, but doesn't on 0.5(.1)
```
(require '[uncomplicate.clojurecuda.core :refer :all])
(init)
(uncomplicate.commons.core/info (device 0))
```
StackOverflowError   uncomplicate.clojurecuda.internal.impl/eval11036/fn--11039 ([impl.clj:46](https://github.com/uncomplicate/clojurecuda/blob/master/src/clojure/uncomplicate/clojurecuda/internal/impl.clj#L45))

**Comment by blueberry** [comment]
Thanks for reporting this. I reproduced it and fixed it. Fix will be available shortly.
